### ISSUE TITLE
CSV Import

### ISSUE THREAD

**Issue by KoshaK0** [WPManageNinja/ninja-tables#4]
Hi, 
strange bug
when importing CSV and the Row data have the Word "New" - this line is skipped and the Table Result become corrupted and does not display well. I had to remove word "New" everywhere and add it after Import.
Regards,
Kos

**Comment by techjewel** [comment]
would you please share the csv file that you want to import.

**Comment by KoshaK0** [comment]
Hi! That was the quickest support reply I have ever had ;o))

 

File attached. The first column have few lines with Word “New”

**Comment by techjewel** [comment]
I did not get the file actually. Please email the file at cep.jewel@gmail.com

thanks

**Comment by KoshaK0** [comment]
issue sorted
