### ISSUE TITLE
Tables are not really responsive

### ISSUE THREAD

**Issue by agringaus** [WPManageNinja/ninja-tables#7]
1) Can't use superscript in rows within the text
2) Can't find where are the options to re-sort the tables. I inserted the tables from the top to the bottom, but the result table shows my last row as a first one
3) The table looks terrible on a smartphone. It's just a table. what makes it a Responsive Ninja Table? what am I doing wrong? http://mylearningspringboard.com/gre/

Thanks.

**Comment by techjewel** [comment]
Hi @agringaus,
1. In the editor, I did not added superscript but you can write html and it will render just fine
2. In Table Configuration, You can specify the data sorting for frontend. You can sort by any column value / created at value. and also you can select ASC / DESC order.
3. Please check the following tutorial for responsive breakdown: https://wpmanageninja.com/r/docs/ninja-tables/configure-responsive-breakdowns-for-table/

Thanks
